document.addEventListener('DOMContentLoaded',()=>{
 const DD=window.DISTRICT_DATA;if(!DD)return;
 const indSel=document.querySelector('#mapIndicator'),yearSel=document.querySelector('#mapYear'),wrap=document.querySelector('#districtMap'),tip=document.querySelector('#districtMapTip'),chips=document.querySelector('#provinceChips'),geometrySource=document.querySelector('#geometrySource'),downloads=document.querySelector('#mapDownloads');
 const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[-–—]/g,' ').replace(/\bYSCOS\b/g,'ISCOS').replace(/\s+/g,' ').trim();
 const fmt=(ind,v)=>{if(v==null||!isFinite(+v))return '—';const n=+v,d=ind.decimals??1;if(ind.unit==='%')return n.toLocaleString('es-PE',{minimumFractionDigits:d,maximumFractionDigits:d})+'%';if(ind.unit==='S/')return 'S/ '+n.toLocaleString('es-PE',{maximumFractionDigits:d});if(ind.unit==='personas'||ind.unit==='casos')return n.toLocaleString('es-PE',{maximumFractionDigits:0});return n.toLocaleString('es-PE',{maximumFractionDigits:d})+(ind.unit?' '+ind.unit:'')};
 indSel.innerHTML=DD.indicators.map(i=>`<option value="${i.id}">${i.label}</option>`).join('');indSel.value=DD.defaultIndicator;
 let geo=null,provinceGeo=null,geoLabel='',activeProvince='';
 const current=()=>DD.indicators.find(i=>i.id===indSel.value);
 function fillYears(){const i=current();yearSel.innerHTML=i.years.slice().reverse().map(y=>`<option value="${y}">${y}</option>`).join('');yearSel.value=i.years.includes(DD.defaultYear)?String(DD.defaultYear):String(i.years[i.years.length-1])}
 const key=f=>norm(f.properties.NOMBPROV)+'|'+norm(f.properties.NOMBDIST);
 function colorScale(v,min,max){if(v==null||!isFinite(v))return '#EDF7FB';if(max<=min)return '#70CBEA';const t=Math.max(0,Math.min(1,(v-min)/(max-min)));const a=[218,244,252],b=[0,122,176];return `rgb(${Math.round(a[0]+(b[0]-a[0])*t)},${Math.round(a[1]+(b[1]-a[1])*t)},${Math.round(a[2]+(b[2]-a[2])*t)})`}
 function ringsOf(g){if(!g)return[];if(g.type==='Polygon')return g.coordinates;if(g.type==='MultiPolygon')return g.coordinates.flat();return[]}
 function geometryPoints(g){return ringsOf(g).flat()}
 function pathFor(g,project){const parts=[];ringsOf(g).forEach(r=>{if(!r.length)return;parts.push('M'+r.map((p,i)=>{const [x,y]=project(p);return `${i?'L':''}${x.toFixed(2)},${y.toFixed(2)}`}).join('')+'Z')});return parts.join('')}
 function provinceOverlayDirect(features,project){let out='';features.forEach(f=>{const d=pathFor(f.geometry,project),pts=geometryPoints(f.geometry),prov=norm(f.properties.NOMBPROV);if(d)out+=`<path class="province-boundary" d="${d}"></path>`;if(pts.length){const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),c=project([(Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2]);out+=`<text class="province-label" x="${c[0].toFixed(1)}" y="${c[1].toFixed(1)}" text-anchor="middle">${prov}</text>`}});return out}
 function provinceOverlay(features,project){
   const groups={};features.forEach(f=>{const p=norm(f.properties.NOMBPROV);(groups[p]||(groups[p]=[])).push(f)});
   let lines='',labels='';
   Object.entries(groups).forEach(([prov,fs])=>{
     const edges=new Map(),all=[];
     fs.forEach(f=>ringsOf(f.geometry).forEach(r=>{r.forEach(p=>all.push(p));for(let i=0;i<r.length-1;i++){const a=r[i],b=r[i+1],ka=a.map(n=>(+n).toFixed(6)).join(','),kb=b.map(n=>(+n).toFixed(6)).join(','),k=ka<kb?ka+'|'+kb:kb+'|'+ka;const x=edges.get(k)||{a,b,n:0};x.n++;edges.set(k,x)}}));
     let d='';edges.forEach(e=>{if(e.n===1){const a=project(e.a),b=project(e.b);d+=`M${a[0].toFixed(2)},${a[1].toFixed(2)}L${b[0].toFixed(2)},${b[1].toFixed(2)}`}});if(d)lines+=`<path class="province-boundary" d="${d}"></path>`;
     if(all.length){const xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),c=project([(Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2]);labels+=`<text class="province-label" x="${c[0].toFixed(1)}" y="${c[1].toFixed(1)}" text-anchor="middle">${prov}</text>`}
   });return lines+labels;
 }
 function updateProvinceChips(){if(!geo||!chips)return;const ps=[...new Set(geo.features.map(f=>norm(f.properties.NOMBPROV)))].sort((a,b)=>a.localeCompare(b,'es'));chips.innerHTML='<button class="province-chip'+(!activeProvince?' active':'')+'" data-prov="">Todas</button>'+ps.map(p=>`<button class="province-chip${activeProvince===p?' active':''}" data-prov="${p}">${p}</button>`).join('');chips.querySelectorAll('button').forEach(b=>b.onclick=()=>{activeProvince=b.dataset.prov;updateProvinceChips();render()})}
 function updateMeta(ind,yr,vals,nums){document.querySelector('#mapTitle').textContent=ind.label+' · '+yr;document.querySelector('#mapSource').textContent='Fuente: '+ind.source;document.querySelector('#mapLegend').innerHTML=`<span><i style="background:#EDF7FB"></i>Sin dato</span><span><i style="background:#164FA3"></i>El Tambo</span>${nums.length?`<span>${fmt(ind,Math.min(...nums))} – ${fmt(ind,Math.max(...nums))}</span>`:''}`;const sv=vals['HUANCAYO|EL TAMBO'];document.querySelector('#eltamboValue').textContent=sv==null?'Sin dato':fmt(ind,sv);document.querySelector('#eltamboDetail').textContent=sv==null?`${ind.label} · ${yr}: la fuente no reporta un valor para El Tambo.`:`${ind.label} en El Tambo · ${yr}.`;document.querySelector('#eltamboRanking').textContent=nums.length?`${nums.length} distritos cuentan con dato para este indicador y año.`:''}
 function currentRows(ind,yr,vals){const rows=[['Provincia','Distrito','Año','Indicador','Valor','Unidad','Fuente']];if(geo){geo.features.slice().sort((a,b)=>(a.properties.NOMBPROV+' '+a.properties.NOMBDIST).localeCompare(b.properties.NOMBPROV+' '+b.properties.NOMBDIST,'es')).forEach(f=>{const v=vals[key(f)];rows.push([f.properties.NOMBPROV,f.properties.NOMBDIST,+yr,ind.label,v==null?'':+v,ind.unit||'',ind.source])})}else Object.entries(vals).sort((a,b)=>a[0].localeCompare(b[0],'es')).forEach(([k,v])=>{const [prov,dist]=k.split('|');rows.push([prov,dist,+yr,ind.label,+v,ind.unit||'',ind.source])});return rows}
 function setupDownloads(ind,yr,vals){if(!downloads)return;downloads.innerHTML='<button id="mapXlsx">Descargar tabla Excel</button><button id="mapCsv">CSV</button><button id="mapPng">Descargar mapa PNG</button><button id="mapSvg">SVG</button>';const title=`El_Tambo_frente_a_Junin_${ind.label}_${yr}`,rows=currentRows(ind,yr,vals);document.querySelector('#mapXlsx').onclick=()=>JP.downloadRowsXlsx(rows,title);document.querySelector('#mapCsv').onclick=()=>JP.downloadRowsCsv(rows,title);document.querySelector('#mapPng').onclick=()=>JP.downloadChartPng('juninDistrictMapSvg',title);document.querySelector('#mapSvg').onclick=()=>JP.downloadChartSvg('juninDistrictMapSvg',title)}
 function renderFallback(ind,yr,vals){const entries=Object.entries(vals).sort((a,b)=>a[0].localeCompare(b[0],'es'));wrap.innerHTML=`<div class="map-fallback"><div><b>No se pudo cargar la geometría del mapa.</b><span>La comparación de datos sigue disponible:</span></div><div class="map-fallback-grid">${entries.map(([k,v])=>{const [prov,dist]=k.split('|');return `<div class="map-fallback-item${dist==='EL TAMBO'&&prov==='HUANCAYO'?' is-eltambo':''}"><span>${dist}</span><small>${prov}</small><strong>${fmt(ind,v)}</strong></div>`}).join('')}</div></div>`;setupDownloads(ind,yr,vals)}
 function render(){
   const ind=current(),yr=String(yearSel.value),vals=ind.values[yr]||{},nums=Object.values(vals).map(Number).filter(Number.isFinite);updateMeta(ind,yr,vals,nums);if(geometrySource)geometrySource.textContent=geoLabel;if(!geo){renderFallback(ind,yr,vals);return;}
   const feats=activeProvince?geo.features.filter(f=>norm(f.properties.NOMBPROV)===activeProvince):geo.features;const all=geo.features.flatMap(f=>geometryPoints(f.geometry));const xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);const W=900,H=660,pad=18,scale=Math.min((W-2*pad)/(xmax-xmin),(H-2*pad)/(ymax-ymin));const ox=(W-(xmax-xmin)*scale)/2,oy=(H-(ymax-ymin)*scale)/2;const project=([x,y])=>[ox+(x-xmin)*scale,H-(oy+(y-ymin)*scale)];const min=nums.length?Math.min(...nums):0,max=nums.length?Math.max(...nums):1;
   let svg=`<svg id="juninDistrictMapSvg" viewBox="0 0 ${W} ${H}" class="junin-district-svg" role="img" aria-label="Mapa de distritos de Junín con límites provinciales">`;
   geo.features.forEach((f,idx)=>{const k=key(f),v=vals[k],prov=norm(f.properties.NOMBPROV),isTarget=norm(f.properties.NOMBDIST)==='EL TAMBO'&&prov==='HUANCAYO',fill=isTarget?'#164FA3':colorScale(v,min,max),op=activeProvince&&prov!==activeProvince&&!isTarget?0.17:1;svg+=`<path class="district-shape${isTarget?' is-eltambo':''}" data-idx="${idx}" d="${pathFor(f.geometry,project)}" fill="${fill}" opacity="${op}"></path>`});
   svg+=(provinceGeo?provinceOverlayDirect(provinceGeo.features,project):provinceOverlay(geo.features,project));svg+='</svg>';wrap.innerHTML=svg;setupDownloads(ind,yr,vals);
   wrap.querySelectorAll('.district-shape').forEach(el=>{el.addEventListener('pointermove',e=>{const f=geo.features[+el.dataset.idx],v=vals[key(f)],name=f.properties.NOMBDIST,prov=f.properties.NOMBPROV;tip.innerHTML=`<b>${name}</b><span>Provincia de ${prov}</span>${v==null?'':`<strong>${fmt(ind,v)}</strong>`}`;tip.classList.add('show');const r=wrap.getBoundingClientRect();let x=e.clientX-r.left+14,y=e.clientY-r.top+14;const tw=tip.offsetWidth||180,th=tip.offsetHeight||80;if(x+tw>r.width-8)x=e.clientX-r.left-tw-14;if(y+th>r.height-8)y=e.clientY-r.top-th-14;tip.style.left=x+'px';tip.style.top=y+'px'});el.addEventListener('pointerleave',()=>tip.classList.remove('show'))})
 }
 fillYears();indSel.onchange=()=>{fillYears();render()};yearSel.onchange=render;render();
 const official="https://www.idep.gob.pe/geoportal/rest/services/DATOS_GEOESPACIALES/L%C3%8DMITES/FeatureServer/5/query?where=NOMBDEP%3D%27JUNIN%27&outFields=UBIGEO%2CNOMBDEP%2CNOMBPROV%2CNOMBDIST&returnGeometry=true&outSR=4326&f=geojson";
 const officialProv="https://www.idep.gob.pe/geoportal/rest/services/DATOS_GEOESPACIALES/L%C3%8DMITES/FeatureServer/4/query?where=NOMBDEP%3D%27JUNIN%27&outFields=IDPROV%2CNOMBDEP%2CNOMBPROV&returnGeometry=true&outSR=4326&f=geojson";
 const urls=[{url:official,label:'Cartografía: IGN / IDEP · límites distritales y provinciales de referencia',official:true},{url:'https://cdn.jsdelivr.net/gh/juaneladio/peru-geojson@master/peru_distrital_simple.geojson',label:'Cartografía simplificada de respaldo · límites distritales'},{url:'https://raw.githubusercontent.com/juaneladio/peru-geojson/master/peru_distrital_simple.geojson',label:'Cartografía simplificada de respaldo · límites distritales'}];
 async function loadGeo(){for(const src of urls){try{const r=await fetch(src.url,{cache:'force-cache'});if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json();const features=(j.features||[]).filter(f=>norm(f.properties&&f.properties.NOMBDEP)==='JUNIN');if(features.length>100){geo={type:'FeatureCollection',features};geoLabel=src.label;if(src.official){try{const pr=await fetch(officialProv,{cache:'force-cache'});if(pr.ok){const pj=await pr.json(),pfs=(pj.features||[]).filter(f=>norm(f.properties&&f.properties.NOMBDEP)==='JUNIN');if(pfs.length>=9)provinceGeo={type:'FeatureCollection',features:pfs}}}catch(e){console.warn('Mapa: límite provincial oficial no disponible',e)}}updateProvinceChips();render();return}}catch(e){console.warn('Mapa: fuente no disponible',src.url,e)}}geoLabel='La cartografía no pudo cargarse; se muestra respaldo tabular.';render()}
 loadGeo();
});